name: Build and test UPM packages for platforms, all branches except main

on:
  pull_request:
    branches-ignore:    
      - 'main'
  # Ignore PRs targetting main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Check Unity version requird by the package
  validate-environment:
    name: Get Unity Version from UPM package
    uses: realitycollective/reusableworkflows/.github/workflows/getunityversionfrompackage.yml@v2-beta
    with:
      build-host: ubuntu-latest

  # Validate output parameters from the Validate-Environment job
  Check-Params-unityversion:
    needs: validate-environment
    uses: realitycollective/reusableworkflows/.github/workflows/testparams.yml@v2-beta
    name: Test output from Validate
    with:
      build-host: ubuntu-latest
      teststring: ${{ needs.validate-environment.outputs.unityversion }}

  # Check Unity Hub and Editor Environment
  Validate-Unity:
    name: Validate Unity Install
    needs: validate-environment
    uses: realitycollective/reusableworkflows/.github/workflows/validateunityinstall.yml@v2-beta
    with:
      build-target: windows
      unityversion: ${{ needs.validate-environment.outputs.unityversion }}


  # Validate output parameters from the Validate-Environment job
  Check-Params-unityeditorversion:
    needs: Validate-Unity
    uses: realitycollective/reusableworkflows/.github/workflows/testparams.yml@v2-beta
    name: Test output from Validate
    with:
      build-host: ubuntu-latest
      teststring: ${{ needs.Validate-Unity.outputs.unityeditorversion }}   

  # Run Unity unit tests defined in the package
  Run-Unit-Tests:
    name: Run Unity Unit Tests
    needs: Validate-Unity
    uses: realitycollective/reusableworkflows/.github/workflows/rununityUPMbuild.yml@v2-beta
    with:
      unityversion: ${{ needs.Validate-Unity.outputs.unityeditorversion }}
      dependencies: '{"development": "github.com/realitycollective/com.realitycollective.buildtools.git"}'
    secrets: inherit